# Generated by Django 3.2.7 on 2021-09-27 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ease_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='benefits',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='quote',
            field=models.TextField(max_length=5000),
        ),
    ]
