# Generated by Django 3.2.7 on 2021-09-29 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ease_app', '0004_auto_20210929_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.TextField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
