# Generated by Django 3.2.7 on 2021-09-29 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ease_app', '0005_auto_20210929_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(default='', max_length=100),
        ),
    ]
